import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, readdir, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { buildContent } from './content.mjs';
import { loadSite, siteTokens } from './site-config.mjs';

test('external content stays untouched and site identity comes only from data', async t => {
  const base = await mkdtemp(join(tmpdir(), 'rhine-external-content-'));
  t.after(() => rm(base, { recursive: true, force: true }));
  const root = join(base, 'data'), output = join(base, 'engine-output');
  await mkdir(join(root, 'notes'), { recursive: true });
  const settings = { title: 'An independent site', brand: 'A & <B>', author: 'Another Author', url: 'https://notes.example.org', githubUrl: 'https://github.com/example', intro: 'Custom introduction', headline: 'My\nnotes', headlineEmphasis: 'today.', projectLinkPrefixes: ['https://projects.example.org/'], projectTitleAliases: { tool: 'Featured tool' } };
  await writeFile(join(root, 'site.json'), JSON.stringify(settings));
  await writeFile(join(root, 'index.md'), '# Home\n\n[tool](https://projects.example.org/tool): A useful project');
  await writeFile(join(root, 'notes/new.md'), '---\norder: 0\n---\n# A new note\n\n[asset](figure.svg)\n\n## Evidence\n\nBody.');
  await writeFile(join(root, 'notes/figure.svg'), '<svg xmlns="http://www.w3.org/2000/svg"/>');
  const before = (await readdir(root, { recursive: true })).sort();
  const result = await buildContent(root, output);
  assert.deepEqual((await readdir(root, { recursive: true })).sort(), before);
  assert.equal(await readFile(join(root, 'site.json'), 'utf8'), JSON.stringify(settings));
  assert.equal(result.records[0].title, 'A new note');
  assert.ok(result.records.some(record => record.title === 'Featured tool' && record.source === 'https://projects.example.org/tool'));
  assert.ok(result.records.every(record => record.lead === settings.author));
  const generated = JSON.parse(await readFile(join(output, 'site-records.json'), 'utf8'));
  assert.equal(generated.site.title, settings.title);
  const html = await readFile(join(output, 'pages/notes/new/index.html'), 'utf8');
  assert.match(html, /A &amp; &lt;B&gt;/);
  assert.match(html, /https:\/\/notes.example.org\/notes\/new/);
  assert.match(html, /BY ANOTHER AUTHOR/);
  assert.match(await readFile(join(output, 'catalogue.html'), 'utf8'), /Custom introduction/);
  assert.match(await readFile(join(output, 'pages/robots.txt'), 'utf8'), /https:\/\/notes.example.org\/sitemap.xml/);
  assert.ok(!html.includes('Tomahawkd'));
  await readFile(join(output, 'pages/notes/figure.svg'));
  const site = await loadSite(root);
  assert.equal(siteTokens('{{site.brand}}', site), 'A &amp; &lt;B&gt;');
  await writeFile(join(root, 'site.json'), '{"url":"javascript:alert(1)"}');
  await assert.rejects(loadSite(root), /HTTP/);
});
